/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.acme.store.products.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductEntity service. Represents a row in the &quot;ACME_ProductEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.acme.store.products.model.impl.ProductEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.acme.store.products.model.impl.ProductEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductEntity
 * @generated
 */
@ProviderType
public interface ProductEntityModel
	extends BaseModel<ProductEntity>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product entity model instance should use the {@link ProductEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this product entity.
	 *
	 * @return the primary key of this product entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product entity.
	 *
	 * @param primaryKey the primary key of this product entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product entity.
	 *
	 * @return the uuid of this product entity
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product entity.
	 *
	 * @param uuid the uuid of this product entity
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product ID of this product entity.
	 *
	 * @return the product ID of this product entity
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product entity.
	 *
	 * @param productId the product ID of this product entity
	 */
	public void setProductId(long productId);

	/**
	 * Returns the group ID of this product entity.
	 *
	 * @return the group ID of this product entity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product entity.
	 *
	 * @param groupId the group ID of this product entity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product entity.
	 *
	 * @return the company ID of this product entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product entity.
	 *
	 * @param companyId the company ID of this product entity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product entity.
	 *
	 * @return the user ID of this product entity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product entity.
	 *
	 * @param userId the user ID of this product entity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product entity.
	 *
	 * @return the user uuid of this product entity
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product entity.
	 *
	 * @param userUuid the user uuid of this product entity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product entity.
	 *
	 * @return the user name of this product entity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product entity.
	 *
	 * @param userName the user name of this product entity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this product entity.
	 *
	 * @return the create date of this product entity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product entity.
	 *
	 * @param createDate the create date of this product entity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product entity.
	 *
	 * @return the modified date of this product entity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product entity.
	 *
	 * @param modifiedDate the modified date of this product entity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category of this product entity.
	 *
	 * @return the category of this product entity
	 */
	public int getCategory();

	/**
	 * Sets the category of this product entity.
	 *
	 * @param category the category of this product entity
	 */
	public void setCategory(int category);

	/**
	 * Returns the name of this product entity.
	 *
	 * @return the name of this product entity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product entity.
	 *
	 * @param name the name of this product entity
	 */
	public void setName(String name);

	/**
	 * Returns the price of this product entity.
	 *
	 * @return the price of this product entity
	 */
	public Double getPrice();

	/**
	 * Sets the price of this product entity.
	 *
	 * @param price the price of this product entity
	 */
	public void setPrice(Double price);

	/**
	 * Returns the stocked of this product entity.
	 *
	 * @return the stocked of this product entity
	 */
	public boolean getStocked();

	/**
	 * Returns <code>true</code> if this product entity is stocked.
	 *
	 * @return <code>true</code> if this product entity is stocked; <code>false</code> otherwise
	 */
	public boolean isStocked();

	/**
	 * Sets whether this product entity is stocked.
	 *
	 * @param stocked the stocked of this product entity
	 */
	public void setStocked(boolean stocked);

	@Override
	public ProductEntity cloneWithOriginalValues();

}